# files are expected to be under config/staches/

# thanks to http://therantsandraves.com/?p=602 for these 'staches
-
  filename: mustache_03.png
  vert_offset: 15
-
  filename: colonel_mustard.png
  vert_offset: 40
  mouth_overlap: 100
-
  filename: mustache_04.png
  vert_offset: 30
  mouth_overlap: 50
  -
  filename: mustache_07.png
  vert_offset: 30
  mouth_overlap: 50
-
  filename: grand-handlebar.png
  vert_offset: 30
  mouth_overlap: 150
-
  filename: painters-brush.png
  vert_offset: 20
  mouth_overlap: 125
-
  filename: petite-handlebar.png
  vert_offset: 0
  mouth_overlap: 60
-
  filename: mustache_11.png
  vert_offset: 40
  mouth_overlap: 70
-
  filename: mustache_12.png
  vert_offset: 45
  mouth_overlap: 45
-
  filename: mustache_13.png
  vert_offset: 10
  mouth_overlap: 0
  -
  filename: mustache_13_red.png
  vert_offset: 10
  mouth_overlap: 0

